export class Product { //Product class  as generated by ng generate class
    constructor( //declared by prefixing constructor argument with Access Modifier. 
        //paremeter properties
        public id: string,
        public sku: string,
        public name: string,
        public description: string,
        public unitPrice: number,
        public imageUrl: string,
        public active: boolean,
        public unitsInStock: number,
        public dateCreated: Date,
        public lastUpdated: Date     
        ){ //this minimizes the boilerplate code automagically

    }
}
